name: Build Windows Electron App

on:
  push:
    paths:
      - "package.json" # Trigger the workflow when package.json changes (e.g., version update)

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Ensure compatibility with your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Electron app
      - name: Build Electron app for Windows
        run: npm run build:win

      # Create a Git tag for the version build (Windows-compatible)
      - name: Create Git tag
        id: tag
        run: |
          $version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
          git tag -a "v$version" -m "Release v$version"
          git push origin "v$version"
        shell: pwsh

      # Create a GitHub release and attach artifacts
      - name: Create GitHub release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ steps.tag.outputs.VERSION }}
          release_name: Release ${{ steps.tag.outputs.VERSION }}
          body: |
            Release of version ${{ steps.tag.outputs.VERSION }}.
          draft: false
          prerelease: false

      - name: Upload build artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.exe
          asset_name: windows-build.exe
          asset_content_type: application/vnd.microsoft.portable-executable
